performance:
  # Database connection pooling
  database:
    postgres:
      max: 20 # maximum number of clients in the pool
      idleTimeoutMillis: 30000
      connectionTimeoutMillis: 2000

    mongodb:
      maxPoolSize: 100
      minPoolSize: 5
      maxIdleTimeMS: 30000
      serverSelectionTimeoutMS: 5000

  # Caching configuration
  cache:
    redis:
      host: 'redis'
      port: 6379
      ttl: 3600 # 1 hour default TTL
      maxMemoryPolicy: 'allkeys-lru'

    nodeCache:
      stdTTL: 600 # 10 minutes
      checkperiod: 120 # 2 minutes
      maxKeys: 1000

  # File upload limits
  upload:
    maxFileSize: 104857600 # 100MB
    allowedMimeTypes:
      images: ['image/jpeg', 'image/png', 'image/webp', 'image/gif']
      videos: ['video/mp4', 'video/webm', 'video/ogg']
      documents:
        [
          'application/pdf',
          'application/msword',
          'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ]
